package fount;

typedef BoolTools = fount.base.BoolTools;
typedef Buffer<T> = fount.base.Buffer<T>;
typedef BufferTools = fount.base.Buffer.BufferTools;
typedef Debug = fount.base.Debug;
typedef Display = fount.base.Display;
typedef Eq<T> = fount.base.Eq<T>;
typedef EqTools = fount.base.Eq.EqTools;
typedef FloatTools = fount.base.FloatTools;
typedef Hash = fount.base.Hash;
typedef Hasher = fount.base.Hash.Hasher;
typedef IBuffer<T> = fount.base.Buffer.IBuffer<T>;
typedef IDebug = fount.base.Debug.IDebug;
typedef IDisplay = fount.base.Display.IDisplay;
typedef IEq<T> = fount.base.Eq.IEq<T>;
typedef IHash = fount.base.Hash.IHash;
typedef IHasher = fount.base.Hash.IHasher;
typedef IOrd<T> = fount.base.Ord.IOrd<T>;
typedef IntTools = fount.base.IntTools;
typedef Option<T> = haxe.ds.Option<T>;
typedef OptionTools = fount.base.OptionTools;
typedef Ord<T> = fount.base.Ord<T>;
typedef OrdTools = fount.base.Ord.OrdTools;
typedef PairTools = fount.base.PairTools;
typedef Queue<T> = fount.base.Queue<T>;
typedef Stack<T> = fount.base.Stack<T>;
typedef StringTools = fount.base.StringTools;
